environment:
  matrix:
    - MSYSTEM: MINGW32
    - MSYSTEM: MINGW64

install:
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "pacman --noconfirm -S --needed base-devel ${MINGW_PACKAGE_PREFIX}-toolchain ${MINGW_PACKAGE_PREFIX}-libevent"

build_script:
  - set HOME=.
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "./autogen.sh"
  - sh -l -c "./configure --enable-werror || { cat config.log; exit 1; }"
  - sh -l -c "make"
  - sh -l -c "make install"

test_script:
  - set HOME=.
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "make -C test all"
#TODO:  - sh -l -c "make -C test run"
